#!/usr/bin/env python3
#USAGE: SSH into here and then say "nohup ./templogg.py &" and then you may leave and the logger continues. Should output one text file each month.
import serial
import RPi.GPIO as GPIO
import time
import datetime
from gpiozero import CPUTemperature

loggername = "px1"
starter = datetime.datetime.now()
loggstartmnd = 0
loggstartdag = 0
loggstarttime = 0
loggstartminutt = 1


if __name__ == '__main__':
	now = datetime.datetime.now()
	while now.minute!=starter.minute+loggstartminutt:
		now = datetime.datetime.now()
		time.sleep(5)
		print("Temperature logging will start in ")
		print(now.minute)
	if now.day==starter.day+loggstartdag and now.hour==starter.hour+loggstarttime and now.minute==starter.minute+loggstartminutt :
		while True:
			logging = open( loggername + "month" + str(now.month) + ".txt","a")	
			cpu = CPUTemperature()
			now = datetime.datetime.now()
			print(cpu.temperature)
			logging.write(str(cpu.temperature) + " Degrees C " + " The " +  str(now.day) + " day of month " +str(now.month) + " at " + str(now.hour) + " huors " + str(now.minute) + " minutes" + "\n" )	
			logging.close()
			time.sleep(60)
			
